name: trichterapp
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  animate_gradient: ^0.0.2+1
  device_preview: ^1.1.0
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_blue: ^0.8.0
  flutter_bluetooth_serial: ^0.4.0
  flutter_localizations:
    sdk: flutter
  flutter_randomcolor: ^1.0.14
  http: ^1.1.0
  intl: ^0.18.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  web_socket_channel: ^2.4.0
  wifi_iot: ^0.3.18+1
  wifi_scan: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
